### PR TITLE
feat: add migration block

### PR DESCRIPTION
**Pull request by steveoh**
i think this is a good block to have for deprecations that we can point folks to and persist instead of only being available in tweets etc.

### CODE REVIEW

**Review by jacobdadams — APPROVED** [review]
I like this idea. Should we have some example text in the body to help people, something like `This dataset has been replaced with SGID.GROUPNAME.TableName`?

**Review by stdavis — APPROVED** [review]

**Comment by ZachBeck** [comment]
works for me.

**Comment by steveoh** [comment]
Is that example text ok?

**Comment by ZachBeck** [comment]
`The replaced data is still accessible via our shelved policy in AGOL`
I think there are cases where it doesn't make sense to shelve the data and deleting it altogether is a better route (i.e. BusStops_UTA and BusRoutes_UTA)

**Comment by steveoh** [comment]
> `The replaced data is still accessible via our shelved policy in AGOL`
> I think there are cases where it doesn't make sense to shelve the data and deleting it altogether is a better route (i.e. BusStops_UTA and BusRoutes_UTA)

Right, that is why this comment is there

> this is here to help the writing juices flow. feel free to completely replace this or simply fill in the blanks

**Review by stdavis — APPROVED** [review]

**Review by jacobdadams — APPROVED** [review]

**Review by ZachBeck — APPROVED** [review]

**Pull request merged**
